feat(core): defer loading of packages and improve startup time
- Added `:defer t` to `use-package` declarations for `general`, `which-key`, and `buttercup`.
- Modified `pre-push` hook to always run tests.
- Added startup time message to `init.el`.
- Updated `package-manager.el` to use hooks for version freezing and package syncing.

diff --git a/.github/hooks/pre-push b/.github/hooks/pre-push
--- a/.github/hooks/pre-push
+++ b/.github/hooks/pre-push
@@ -7,14 +7,13 @@ REPO_ROOT="$DIR/../.."
 #* Change to repo root
 cd "$REPO_ROOT"
 
-#* Run tests if any .el files changed
-if  git diff --name-only HEAD@{upstream} | grep -q "\.el$"; then
-    echo "Running tests..."
-    make test
-    if [ $? -ne 0 ]; then
-        echo "Error: Tests failed. Push aborted."
-        exit 1
-    fi
+# Run tests
+
+echo "Running tests..."
+make test
+if [ $? -ne 0 ]; then
+    echo "Error: Tests failed. Push aborted."
+    exit 1
 fi
 
 #* Run docs
